### ISSUE TITLE
这个可以直接部署到github page上吗？

### ISSUE THREAD

**Issue by willard-yuan** [zhouningyi/openWedding#1]
Hi, 宁奕
好基友结婚，想做个祝福网页送给他，于是跑到你这来了。这个**openWedding**一进去看的时候，第一感觉就是震惊（背景乐也很震惊）。我想问一下，这个可以直接到github page上吗？如果可以的话，我部署到github page上后[wedding](http://yongyuan.name/wedding/)，并没全部复原你的[openwedding.org](http://openwedding.org/)中的效果，急切希望得到大神的回复。

**Comment by zhouningyi** [comment]
好的 期待你的效果哈 如果有问题 可以联系我  1八357138841

**Comment by willard-yuan** [comment]
多谢大神回复，部署到github上后的演示效果在这里：[演示地址](http://yongyuan.name/wedding/)，没有完全复原，你这个不是纯HTML5了吗，我是不是缺少了某些东西？

**Comment by zhouningyi** [comment]
不好意思回复晚了 我看线上已经在运行。那时候不会数据库 当时为了归档方便 用文件夹整理数据，然后需要在data/3worldwishes里按照顺序放照片 最后用bin/genconfig处理一次（nodejs脚本）生成一个静态资源json。 这个脚本忘记加了 补上。

**Comment by zhouningyi** [comment]
你也可以加我微信 zhouningyi1 我这看的不勤快

**Comment by willard-yuan** [comment]
好的，多谢宁奕大哥，。我已经完全复现了~openwedding.org~的效果，这个部署到github上完全没问题，当时部署的时候没怎么细看代码，然后用浏览器调试了一下，发现了问题，最后解决了。回去加你微信哈。
