### ISSUE TITLE
你好 请问下你的这些照片都是怎么获得的啊

### ISSUE THREAD

**Issue by Freedom000** [zhouningyi/openWedding#3]
你好 真的感觉这个求婚方式很适合像我们这种码农同行 也是挺浪漫的一种方式 想问下 你这些照片是如何获得的啊  是每个人都在举着纸片 然后拍的照片吗  你是怎么获得的啊  表示想跟女友来个这种形式的求婚或是结婚典礼背景

**Comment by Freedom000** [comment]
@zhouningyi

**Comment by willard-yuan** [comment]
@Freedom000 这些照片都是宁奕哥远在五湖四海的朋友拍的，宁奕哥曾骑行远游四方~

**Comment by zhouningyi** [comment]
@Freedom000 是找朋友拍的，正好相关的朋友比较多

**Comment by Freedom000** [comment]
@zhouningyi @willard-yuan  哦哦  好的 好的

**Comment by Kevin-chenyang** [comment]
我觉得这个项目很有意思,很特别,我想问现在这个支持定制吗?

**Comment by zhouningyi** [comment]
您好 都是户外圈的朋友帮忙拍的





在 2019-10-14 13:10:27，"Kevin-chenyang" <notifications@github.com> 写道：


我觉得这个项目很有意思,很特别,我想问现在这个支持定制吗?

**Comment by Freedom000** [comment]
@zhouningyi  你好 我又来了 想问下 这个代码什么的可以分享吗 或者 可以借用下吗  想跟老婆求婚 也弄个这样的 在本地弄

**Comment by zhouningyi** [comment]
代码都在github上 可以用的






在 2019-10-24 09:26:40，"Freenovo" <notifications@github.com> 写道：


@zhouningyi 你好 我又来了 想问下 这个代码什么的可以分享吗 或者 可以借用下吗 想跟老婆求婚 也弄个这样的 在本地弄

**Comment by Freedom000** [comment]
Very thanks!!!  之前没下全 时间久远 忘记了。。。现在OK了~~~
